routes/admin.php
<?php

Route::group(['prefix' => 'admin','namespace'=>'Admin'], function() {
    Route::get('/login', ['as' => 'admin.getLogin', 'uses' => 'AuthController@showLoginForm'])->middleware(['guest:admin','guest']);
    //kalau user sudah login,lalu mau mengarah ke login admin akan di lempar balik ke home...
    Route::post('/login', ['as' => 'admin.postLogin', 'uses' => 'AuthController@login']);
    Route::post('/logout', ['as' => 'admin.getLogout', 'uses' => 'AuthController@logout']);

    Route::group(['middleware' => ['auth.admin:admin']], function() {
        Route::get('/', ['as' => 'admin.home', 'uses' => 'AdminController@index']);
    });
    
    /*ARTICLE CMS*/
    Route::group(['prefix' => 'article'],function(){
        Route::get('/view','ArticleController@index')->name('admin.article.index');
        Route::get('/create','ArticleController@create')->name('admin.article.create');
        Route::post('/create','ArticleController@store')->name('admin.article.store');
        Route::get('/{id}/edit','ArticleController@edit')->name('admin.article.edit');
        Route::put('/{id}/edit','ArticleController@update')->name('admin.article.update');
        Route::delete('/delete/{id}','ArticleController@destroy')->name('admin.article.destroy');
        Route::post('/approve','ArticleController@bulkAction')->name('admin.article.approve');
    });
    
    /*CATEGORY CMS*/
    Route::group(['prefix' => 'category'],function(){
        Route::get('/view','CategoryController@index')->name('admin.category.index');
        Route::get('/preview/{id}','CategoryController@show')->name('admin.category.show')->where('id','[0-9]+');
        Route::get('/create','CategoryController@create')->name('admin.category.create');
        Route::post('/create','CategoryController@store')->name('admin.category.store');
        Route::get('/{id}/edit','CategoryController@edit')->name('admin.category.edit');
        Route::put('/{id}/edit','CategoryController@update')->name('admin.category.update');
        Route::delete('/delete/{id}','CategoryController@destroy')->name('admin.category.destroy');
    });
    
    /*USER MANAGEMENT CMS*/
    Route::group(['prefix' => 'usermanagement'],function(){
        Route::get('/view','UserManagementController@index')->name('admin.usermanagement.index');
        Route::get('/preview/{id}','UserManagementController@show')->name('admin.usermanagement.show')->where('id','[0-9]+');
        Route::get('/create','UserManagementController@create')->name('admin.usermanagement.create');
        Route::post('/create','UserManagementController@store')->name('admin.usermanagement.store');
        Route::get('/{id/edit}','UserManagementController@edit')->name('admin.usermanagement.edit');
        Route::put('/{id/edit}','UserManagementController@update')->name('admin.usermanagement.update');
        Route::delete('/delete/{id}','UserManagementController@destroy')->name('admin.usermanagement.destroy');
    });
    
    Route::get('/changepassword','AdminController@changePasswordView')->name('admin.changepass');
    Route::put('/changepassword/{id}','AdminController@changePasswordStore')->name('admin.storepass')->where('id','[0-9]+');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/','HomeController@landingPage');

Auth::routes();

Route::get('/home', 'UserController@index');

Route::get('/view/{slug?}','HomeController@detail')->name('blog.view');

/*Route::group(['prefix' => 'article'],function(){
    Route::get('/view','ArticleController@index')->name('article.index');
    Route::get('/preview/{id}','ArticleController@show')->name('article.show')->where('id','[0-9]+');
    Route::get('/create','ArticleController@create')->name('article.create');
    Route::post('/create','ArticleController@store')->name('article.store');
    Route::get('/edit/{id}','ArticleController@edit')->name('article.edit');
    Route::put('/edit/{id}','ArticleController@update')->name('article.update');
    Route::delete('/delete/{id}','ArticleController@destroy')->name('article.destroy');
});*/

/*Route::group(['prefix' => 'category'],function(){
    Route::get('/view','CategoryController@index')->name('category.index');
    Route::get('/preview/{id}','CategoryController@show')->name('category.show')->where('id','[0-9]+');
    Route::get('/create','CategoryController@create')->name('category.create');
    Route::post('/create','CategoryController@store')->name('category.store');
    Route::get('/edit/{id}','CategoryController@edit')->name('category.edit');
    Route::put('/edit/{id}','CategoryController@update')->name('category.update');
    Route::delete('/delete/{id}','CategoryController@destroy')->name('category.destroy');
});*/

Route::resource('article','ArticleController');
Route::resource('category','CategoryController');
Route::resource('article.comment', 'CommentController');

Route::get('/socialauth/{provider}','SocialController@redirect');
Route::get('/socialauth/{provider}/callback','SocialController@callback');

Route::get('/changepassword','UserController@changePasswordView')->name('user.changepass');
Route::put('/changepassword/{id}','UserController@changePasswordStore')->name('user.storepass')->where('id','[0-9]+');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'article_id', 'user_id', 'comment',
    ];
    
    public function getCreatedAtAttribute($date) {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('M d, Y H:i'); 
    }
    
    public function articles(){
        return $this->belongsTo('App\Articles','article_id'); //merubah foreign key
    }
    
    public function users(){
        return $this->belongsTo('App\User','user_id'); //merubah foreign key
    }
}

resources/views/article_detail.blade.php
@extends('layouts.blog')


@section('content')
    <!-- Title -->
    <h1>{{$article->title}}</h1>

    <!-- Author -->
    <p class="lead">
        by <a href="#">{{ $article->users->fullname }}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> 
    Posted on {{ substr($article->created_at,0,12) }} at {{ substr($article->created_at,13,5)}}</p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="{{ asset('uploaded_file').'/'.$article->image }}" alt="">

    <hr>

    <!-- Post Content -->
    {!! $article->content !!}

    <hr>

    <!-- Blog Comments -->

    <!-- Comments Form -->
    @if(!Auth::guard('admin')->guest() || !Auth::guest() )
    <div class="well">
        <h4>Leave a Comment:</h4>
        <form role="form" action="{{ route('article.comment.store',$article->id) }}" method="POST">
           {{ csrf_field() }}
            <div class="form-group">
                <textarea name="comment" class="form-control" rows="3"></textarea>
            </div>
            @if ($errors->has('comment'))
                <span class="help-block">
                    <strong>{{ $errors->first('comment') }}</strong>
                </span>
            @endif
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    @else
    <div class="well">
        <h4 class="text-center"><a href="{{ url('login?redirect=').$article->id }}">Login</a> or <a href="{{ url('register?redirect=').$article->id }}">Register</a> to Leave a Comment</h4>
    </div>
    @endif

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    @if($article->comments->count() > 0)
        @foreach($article->comments as $comment)
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">{{ $comment->users->fullname }}
                        <small>{{ substr($comment->created_at,0,12) }} at {{ substr($comment->created_at,13,5)}}</small>
                    </h4>
                    {{ $comment->comment }}
                </div>
            </div>
        @endforeach
    @else
        <h5>Belum Ada Comment</h5>
    @endif     
@endsection

resources/views/home.blade.php
@extends('layouts.cms')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">User Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/landing.blade.php
@extends('layouts.blog')


@section('content')
<h1 class="page-header">
    Welcome to our blog.
</h1>

@foreach($article as $v)
<!-- First Blog Post -->
    <h2>
        <a href="{{ url('/view')."/".$v->slug }}">
            {{ $v->title }}
        </a>
    </h2>
    <p class="lead">
        by <a href="#">
            {{ $v->users->fullname }}
        </a>
    </p>

    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ substr($v->created_at,0,12) }} at {{ substr($v->created_at,13,5)}}</p>
    <hr>
    <img class="img-responsive" src="{{ asset('uploaded_file').'/'.$v->image }}" alt="">
    <hr>
    <p>
        {{ $v->short_description }}
    </p>
    <a class="btn btn-primary" href="{{ url('/view')."/".$v->slug }}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

    <hr>

@endforeach

<!-- Pager -->
{{ $article->appends(compact('q'))->links() }}

@endsection

resources/views/modal_comment.blade.php
<div class="modal modal-primary fade" tabindex="-1" role="dialog" id="commentModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">View Comments</h4>
      </div>
      <div class="modal-body content_comments" data-redirect="{{ $redirect }}">
            Loading...
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/modal_confirm.blade.php
<div class="modal modal-primary fade" tabindex="-1" role="dialog" id="confirmModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Konfirmasi Hapus {{ $modal_title }}</h4>
      </div>
      <div class="modal-body">
        <p>Yakin ingin menghapus {{ strtolower($modal_title) }} ini ? </p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-success hapus_{{ strtolower($modal_title) }}" type="button" onclick="hapus(this)">Iya</button>
        <button class="btn btn-danger" type="button" data-dismiss="modal" >Tidak</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->